server:
  port: 5001
  
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Connection base de données
datasource:
  url:  jdbc:mysql://localhost:3306/dbname
  username: toto
  password: toto

jpa:
  hibernate:
    ddl-auto: create
  database-platform: org.hibernate.dialect.MariaDBDialect
  show-sql: true
